import { GraphQLInputObjectType } from 'graphql';

const inputList = {};

const Input = (inputType, fields) => {
  if (!inputList[inputType]) {
    inputList[inputType] = new GraphQLInputObjectType({
      name: `${inputType}Input`,
      description: `Autogenerated input type of ${inputType}.`,
      fields
    });
  }

  return inputList[inputType];
};

export default Input;
