import { GraphQLObjectType } from 'graphql';

const payloadList = {};

const Payload = (payloadType, fields) => {
  if (!payloadList[payloadType]) {
    payloadList[payloadType] = new GraphQLObjectType({
      name: `${payloadType}Payload`,
      description: `Autogenerated payload type of ${payloadType}.`,
      fields
    });
  }

  return payloadList[payloadType];
};

export default Payload;
